### ISSUE TITLE
HA Component testing

### ISSUE THREAD

**Issue by stboch** [G-Two/subarulink#16]
@G-Two looks like your intergration got tagged for release for .114 Congrats!

**Comment by G-Two** [comment]
Thanks!  Do you think it is too late to commit one last change?  I have locks, beep, blink, remote start/stop implemented as services based upon your recommendation.

**Comment by stboch** [comment]
since the or hasn't merged to dev yet I think it should still be good to go for another update.

**Comment by G-Two** [comment]
@stboch if you get a chance, I'd appreciate any feedback you have on some pending updates I have to the HA integration that removes the lock platform and replaces with a service (along with services for all other remote actuations).  It's in a new branch in my [HA fork](https://github.com/G-Two/home-assistant/tree/add_services)

**Comment by stboch** [comment]
while I hated the annoying unknown state I did like the fact it was a lock it allowed me to use Google assistant day unlock "mysubaru"

**Comment by stboch** [comment]
just had a look over the code will test in the morning. looks good at first glance.

**Comment by G-Two** [comment]
> while I hated the annoying unknown state I did like the fact it was a lock it allowed me to use Google assistant day unlock "mysubaru"

Ok, that's good feedback.  I suppose it doesn't hurt to have both the lock entity and the service available.  I'll put it back right now so that you can test tomorrow.  Thanks.

**Comment by stboch** [comment]
when you get around to refactoring the binary sensors add vehicle state type as a binary one for if the engine is running. not sure yet how often this is not off... but it is at least on when the remote start is running also updates back to off when remote start times out.

**Comment by stboch** [comment]
Looks like there is a catch requiring vin to only be in uppercase, not had a chance to check where that bug is presenting but it might be fine on the HA code to force uppercase the VIN. Otherwise services worked great!

**Comment by G-Two** [comment]
Thanks for catching that.  I added vin.upper() in the HA service handler, as well as added vin.upper() to the public functions in the controller.  I made a few other tweaks and have it running at home now.  If all goes well, I'll merge into the current PR and update the documentation.  

Where does it show subaru is going to be in the 0.114 release?

**Comment by stboch** [comment]
well apparently I was wrong... so sorry. I saw it was added to a new integrations pipeline so I assumed this was used for the release. however I assumed wrong.

**Comment by G-Two** [comment]
no problem, I saw that too.  It's still another step closer.  Looks like started the new pipeline to help new integrations get rolled in.  Gives me a little more time to polish the integration before it hits the HA release.

**Comment by stboch** [comment]
btw others who want to use it only need to copy it I to their custom_componets folder and it all works as it should that is what I have been doing since I first found your project.

**Comment by G-Two** [comment]
@stboch I setup a [new repo](https://github.com/G-Two/homeassistant-subaru) to continue development while the initial PR continues the review (it moved past another wicket last week).  I found the gigantic HA Core repo to be a too unwieldy for development and testing.  Please give this a try when you get a chance, it maintains everything from the original repo, but in a more custom_component friendly directory structure.

**Comment by stboch** [comment]
Already did... got it going happy device tracker is in there. Might be a good option to add the hacs repo code bits if you like. Then people can get it from HACS. Your choice. If you don't figure it out tonight(for me in the US) I'll submit a PR with the changes tomorrow.

**Comment by G-Two** [comment]
The Subaru integration has been approved and merged to the HA dev branch. It will be an official component starting with release 2021.3. It'll only have sensors, so the HACS version is probably still the way to go for existing users now. I plan to eventually submit PRs to carry all features of the HACS version over to the official component.
