### ISSUE TITLE
[Feature] Add ability to stop the current request (Horn / Lights)

### ISSUE THREAD

**Issue by i814u2** [G-Two/subarulink#26]
In the MySubaru app, you can sound the horn, and then stop it, as well. When sounding, it honks every couple of seconds.

With this, you just send a command to request the event and it keeps going. 
I haven't fully tested if there's a timeout, or not, on their side, but it would be nice to be able to send a stop command, if that's possible.

I'm not sure what else to provide, but if I can help with any info, just let me know.

Otherwise, thanks for this, it's awesome.

**Comment by stboch** [comment]
3 things 

1. What model and year car
2. What country are you in
3. Can you provide the debug output you see when you send the request for the horn

**Comment by i814u2** [comment]
Yeah, probably should have guessed that some vehicle info might be helpful. Sorry about that one, here you go:
  Ascent 2020
  United States

Attached debug (went a little wild redacting things, so if I went too far, let me know):
[hornDebug.txt](https://github.com/G-Two/subarulink/files/5660951/hornDebug.txt)

**Comment by stboch** [comment]
Hmm it seems like this should be an easy add @G-Two here are the two services for stopping lights and horn, personally I didn't notice the stop button in the UI always just let it go for the full minute I think...

```
app.remoteServiceG2HornLightsStop = new RemoteService("Stop Horn & Lights", "/service/g2/hornLights/stop.json","/service/g2/remoteService/status.json");
app.remoteServiceG2LightsStop = new RemoteService("Stop Lights", "/service/g2/hornLights/stop.json","/service/g2/remoteService/status.json");
```

**Comment by G-Two** [comment]
Feature added in #27.

**Comment by G-Two** [comment]
@i814u2 feature addition complete.  Thanks for the suggestion.
