### ISSUE TITLE
Don't display VIN on success? 

### ISSUE THREAD

**Issue by RaghavRao** [G-Two/subarulink#33]
I use this on my phone and use Google voice keyboard for hacky Voice activated commands out and about, but I don't like that it shows the VIN number on success. I'd rather it show the vehicle nickname

**Comment by G-Two** [comment]
@RaghavRao it should be fixed now in v0.3.12

**Comment by RaghavRao** [comment]
This is perfect! It shows the nickname!

Thank you!
