### ISSUE TITLE
Anything change? Some entities missing and no services

### ISSUE THREAD

**Issue by mconlow** [G-Two/subarulink#42]
Hi hi, I've been happily using the Home Assistant integration for a while. I recently upgraded to 2021.06 HA and then noticed today that I had a whole bunch of duplicate Subaru entities in HA. I uninstalled the integration and reinstalled it. Now I'm down to 9 entities, and don't have one for location of the car or the ignition status or door lock. There also don't appear to be the door lock service available which I am heavily reliant on.

Wondering if anything has changed recently?

**Comment by stboch** [comment]
are you using Subaru through hacs or as a custom component or the one that is built in to Home-assistant?

**Comment by mconlow** [comment]
built in to Home Assistant

**Comment by stboch** [comment]
the built in currently doesn't support those features you have to use the custom component version to get location, services, and lock features.

**Comment by mconlow** [comment]
ah ok I see that now in the other repository. Thank you!
