### ISSUE TITLE
what is the format of "form_data" parameter in the remote_start function?

### ISSUE THREAD

**Issue by ACiDGRiM** [G-Two/subarulink#46]
It appears that there is existing functionality to specify remote start parameters. Can you please provide any information on how to format this additional parameter?

**Comment by stboch** [comment]
Yes, previously the remote start API call required providing the climate parameters if they were to be set during the remote start. there is a function to update those last set, however I have seen the new "profiles" will need to see how the app has implemented these, if they are included API calls to the same services we use currently I don't see an issue adding the support. Then comes the fun of how to expose it to home-assistant which with the new select might be fine.

**Comment by ACiDGRiM** [comment]
Hopefully it's as simple as sending {"vin": xxxxxxxx, "profile": "Defrost"}

**Comment by stboch** [comment]
NOTES for new g3 service:
/service/g2/climatePresetSettings/fetch.json
`        //     {
        //         "name": "Last In-Car Settings",
        //         "runTimeMinutes": "10",
        //         "includeClimate": false,
        //         "canEdit": "false",
        //         "disabled": "true",
        //         "vehicleType": "gas",
        //         "presetType": "subaruPreset",
        //         "startConfiguration": "START_ENGINE_ALLOW_KEY_IN_IGNITION",
        //     },
        //     {
        //         "name": "Auto",
        //         "runTimeMinutes": "10",
        //         "climateZoneFrontTemp": "74",
        //         "climateZoneFrontAirMode": "AUTO",
        //         "climateZoneFrontAirVolume": "AUTO",
        //         "outerAirCirculation": "auto",
        //         "heatedRearWindowActive": "false",
        //         "airConditionOn": "false",
        //         "heatedSeatFrontLeft": "off",
        //         "heatedSeatFrontRight": "off",
        //         "canEdit": "true",
        //         "disabled": "false",
        //         "vehicleType": "gas",
        //         "presetType": "subaruPreset"
        //     },
        //     {
        //         "name": "Full Cool",
        //         "runTimeMinutes": "10",
        //         "climateZoneFrontTemp": "60",
        //         "climateZoneFrontAirMode": "feet_face_balanced",
        //         "climateZoneFrontAirVolume": "7",
        //         "airConditionOn": "true",
        //         "heatedSeatFrontLeft": "OFF",
        //         "heatedSeatFrontRight": "OFF",
        //         "heatedRearWindowActive": "false",
        //         "outerAirCirculation": "outsideAir",
        //         "startConfiguration": "START_ENGINE_ALLOW_KEY_IN_IGNITION",
        //         "canEdit": "true",
        //         "disabled": "true",
        //         "vehicleType": "gas",
        //         "presetType": "subaruPreset"
        //     },
        //     {
        //         "name": "Full Heat",
        //         "runTimeMinutes": "10",
        //         "climateZoneFrontTemp": "85",
        //         "climateZoneFrontAirMode": "feet_window",
        //         "climateZoneFrontAirVolume": "7",
        //         "airConditionOn": "false",
        //         "heatedSeatFrontLeft": "high_heat",
        //         "heatedSeatFrontRight": "high_heat",
        //         "heatedRearWindowActive": "true",
        //         "outerAirCirculation": "outsideAir",
        //         "startConfiguration": "START_ENGINE_ALLOW_KEY_IN_IGNITION",
        //         "canEdit": "true",
        //         "disabled": "true",
        //         "vehicleType": "gas",
        //         "presetType": "subaruPreset"
        //     },
        //     {
        //         "name": "Full Cool",
        //         "runTimeMinutes": "10",
        //         "climateZoneFrontTemp": "60",
        //         "climateZoneFrontAirMode": "feet_face_balanced",
        //         "climateZoneFrontAirVolume": "7",
        //         "airConditionOn": "true",
        //         "heatedSeatFrontLeft": "OFF",
        //         "heatedSeatFrontRight": "OFF",
        //         "heatedRearWindowActive": "false",
        //         "outerAirCirculation": "outsideAir",
        //         "startConfiguration": "START_CLIMATE_CONTROL_ONLY_ALLOW_KEY_IN_IGNITION",
        //         "canEdit": "true",
        //         "disabled": "true",
        //         "vehicleType": "phev",
        //         "presetType": "subaruPreset"
        //     },
        //     {
        //         "name": "Full Heat",
        //         "runTimeMinutes": "10",
        //         "climateZoneFrontTemp": "85",
        //         "climateZoneFrontAirMode": "feet_window",
        //         "climateZoneFrontAirVolume": "7",
        //         "airConditionOn": "false",
        //         "heatedSeatFrontLeft": "high_heat",
        //         "heatedSeatFrontRight": "high_heat",
        //         "heatedRearWindowActive": "true",
        //         "outerAirCirculation": "outsideAir",
        //         "startConfiguration": "START_CLIMATE_CONTROL_ONLY_ALLOW_KEY_IN_IGNITION",
        //         "canEdit": "true",
        //         "disabled": "true",
        //         "vehicleType": "phev",
        //         "presetType": "subaruPreset"
        //     }`
        
  /service/g2/remoteEngineStartSettings/fetch.json & save.json User presets
  `        //     {
        //         "name": "User Setting2",
        //         "runTimeMinutes": "10",
        //         "climateZoneFrontTemp": "60",
        //         "climateZoneFrontAirMode": "feet_face_balanced",
        //         "climateZoneFrontAirVolume": "7",
        //         "airConditionOn": "true",
        //         "heatedSeatFrontLeft": "OFF",
        //         "heatedSeatFrontRight": "OFF",
        //         "heatedRearWindowActive": "false",
        //         "outerAirCirculation": "outsideAir",
        //         "startConfiguration": "START_ENGINE_ALLOW_KEY_IN_IGNITION",
        //         "canEdit": "true",
        //         "disabled": "false",
        //         "presetType": "userPreset"
        //     }`

**Comment by G-Two** [comment]
I plan to expose climate settings in HA in the next release. Hopefully I can reference the presets feature. But worst case, I can have the individual parameters exposed via a service.

**Comment by ACiDGRiM** [comment]
Thank you, I love when companies break their API, I've been stuck on the same remote start settings since then, which doesn't have the front window defroster turned on :*(

No amount of changing settings in the subaru app remote start saves as the last used settings. I still enjoy having a car I can get in and drive without waiting for it to warm up with this awesome component.

**Comment by stboch** [comment]
@ACiDGRiM The new version is working for me so hopefully this has been fixed for you too!

**Comment by ACiDGRiM** [comment]
I can confirm this works. I did have to reinstall the integration to re-authenticate before it would work. It appears to be resolved.

Closed. Thank you for the great work on this!!! Happy new year.
