### ISSUE TITLE
Error on door unlock

### ISSUE THREAD

**Issue by Derekzielinski** [G-Two/subarulink#49]
On v0.6.0rc2, I get this error when unlocking the doors. Locking works fine. This is directly from the subaru lock entity.

Service unlock failed for _insert_VIN_here_: Invalid door 'all' specified for unlock command.

<img width="394" alt="Screen Shot 2021-12-30 at 9 40 38 AM" src="https://user-images.githubusercontent.com/19964350/147761514-06ac5e23-e39f-4e55-b72c-4183195c64c9.png">

**Comment by G-Two** [comment]
Thank you for reporting that. I made a dumb mistake [here](https://github.com/G-Two/homeassistant-subaru/blob/1912c0c56fc39f340b41a7c5057d1482eef5edc3/custom_components/subaru/lock.py#L84):

```python
    async def async_unlock(self, **kwargs):
        """Send the unlock command."""
        _LOGGER.debug("Unlocking doors for: %s", self.car_name)
        await async_call_remote_service(
            self.hass,
            self.controller,
            SERVICE_UNLOCK,
            self.vehicle_info,
            UNLOCK_DOOR_ALL, # this should be UNLOCK_VALID_DOORS[UNLOCK_DOOR_ALL],
            self.config_entry.options.get(CONF_NOTIFICATION_OPTION),
        )
```
I'll fix in rc3

**Comment by Derekzielinski** [comment]
Working in rc3. Thanks for the quick fix, and for all your work on this!
