### ISSUE TITLE
Blank / Example Config?

### ISSUE THREAD

**Issue by mpalermo73** [G-Two/subarulink#51]
Hi!

Is there a way to generate a blank / framework config, or do you have an example available that my eyes aren't finding?

Thank you!

M.

**Comment by stboch** [comment]
Currently not an example app, but you can look at the [cli](https://github.com/G-Two/subarulink/blob/e60d054cb9b68cd6898fa4b7a53cae108188992f/subarulink/app/cli.py) to see what features and code you need to implement.

**Comment by mpalermo73** [comment]
OK.  I got it.  Thanks for pointing that out!

M.

**Comment by G-Two** [comment]
@mpalermo73 if you're looking for the format of the config file autogenerated/used by the CLI, then it is:
```json
{
    "country": "USA",
    "username": "me@email.com",
    "password": "password",
    "pin": "1234",
    "device_name": "subarulink",
    "save_creds": "Y",
    "device_id": 1628400000,
    "default_vin": "JF2ABCDE6L0000001",
    "remote_start_preset": "FULL HEAT"
}
```
As @stboch mentioned, the CLI code will provide an example to start from if you want to write your own application (you should also take a look at [DEVELOPERS.md](https://github.com/G-Two/subarulink/blob/master/DEVELOPERS.md). There is also an [AWS Lambda](https://github.com/chrisroedig/aws-subaru-api) example. There are others that also just wrap the provided CLI with their own custom script.
