### ISSUE TITLE
Starlink API

### ISSUE THREAD

**Issue by krushil1** [G-Two/subarulink#59]
This isn't certainly an issue but I was curious if one of the devs could provide me with a more straightforward API to interact with my car where I can send remote commands through an easy python script from my terminal.

**Comment by G-Two** [comment]
I'm not sure I understand the ask. Are you looking for more documentation beyond that described in [DEVELOPERS.md](https://github.com/G-Two/subarulink/blob/master/DEVELOPERS.md)? Or are you asking for the python package to be rearchitected to make its API "more straightforward"?.

If all you want to do is send remote commands via a shell, then why not just use the provided CLI utility?
```bash
# example to lock the doors
$ subarulink lock 
```

**Comment by krushil1** [comment]
I just figured it out. I was a bit confused about using it via a shell! But thank you again! Appreciate the help!
