### ISSUE TITLE
Deprecated g2v21- 404 error code

### ISSUE THREAD

**Issue by stboch** [G-Two/subarulink#60]
It looks like Subaru finally deprecated remoteEngineQuickStartSettings ... Will verify when I get a chance to check the App. 
 RequestInfo(url=URL('https://mobileapi.prod.subarucs.com/g2v21/service/g2/remoteEngineQuickStartSettings/save.json'), method='POST'

**Comment by stboch** [comment]
Correction it looks like they have advanced to /g2v24 .. Testing a change

**Comment by G-Two** [comment]
g2v24 imposed some changes to the JSON fields that the Subaru API returns. I think I've taken them all into account in the v0.7.0 branch. v0.7.0rc0 has been published to PyPI.

**Comment by stboch** [comment]
Tested Looks like its working on my two models. 👍
