### ISSUE TITLE
Possible deprication of g2v25 API

### ISSUE THREAD

**Issue by wonderslug** [G-Two/subarulink#77]
Howdy all

Noticed today my Subaru HACS HA integration wasn't working.  Looking at logs its getting a 404 on https://mobileapi.prod.subarucs.com/g2v25/login.json.  Looks like g2v26 and g2v27 are working, so they may only be keeping 2 API version compatibility.

**Comment by stboch** [comment]
@G-Two Tested out v27 and it looks like there aren't any breaking changes.

**Comment by G-Two** [comment]
@wonderslug awesome, thanks for testing. Things look good on my end as well, so I'll publish a new release with the change now.

**Comment by G-Two** [comment]
Fixed with 0.7.6

**Comment by Elycin** [comment]
Hi @G-Two, 

has this made it upstream into the latest version of HASS Core? I was unable to find a pull request to bump the version of the API being consumed.

Thanks.

**Comment by G-Two** [comment]
@Elycin PR is now in HA Core: https://github.com/home-assistant/core/pull/91064 
Hopefully it makes it into 2023.4.2
