### ISSUE TITLE
[CLI Feature Request] Choose climate preset in `subarulink remote_start` instead of always using default

### ISSUE THREAD

**Issue by deltatxv** [G-Two/subarulink#93]
**Background**: Currently, the `remote_start` CLI option always start w/ default preset. I want to choose the climate preset based on my local weather via simple bash script that i run through iOS shortcuts.

**Request**: add optional additional argument for `remote_start` to choose climate preset by name e.g. `subarulink remote_start [climate_preset_name]`

**Comment by deltatxv** [comment]
I've made this change in my forked repo: [https://github.com/deltatxv/subarulink](url)

@G-Two Lmk if you want me to create a PR for this - I'll clean up some of the code and commits.

**Comment by G-Two** [comment]
I tested the new feature and it works great on my end. Please create a PR. Thanks for adding this!

**Comment by deltatxv** [comment]
Thanks for making this tool!

PR here: https://github.com/G-Two/subarulink/pull/94
